### PR TITLE
Created a joystick factory

### PR DESCRIPTION
**Pull request by chasehaddleton**
Note, I am not quite sure what the controller descriptions actually are and I'm not quite sure how to throw an error to the driverstation console.

### CODE REVIEW

**Comment by chasehaddleton** [comment]
I was thinking about making it throw an exception to the driver station upon error, or is that not possible? If we did that, would we still need to restart the code to get it to work?
Not too sure what the values are, we will have to check them. (guess that should have been in a FIXME instead of in the pull request body)

**Comment by AquaBytez** [comment]
I'll be taking this over, since I more or less know how to properly implement it

**Comment by chasehaddleton** [comment]
I actually did fix this branch, but I haven't pushed the updates. Will do that now

**Comment by AquaBytez** [comment]
The R_Extreme3DPro_GameController is missing, so I just commented it out from the GameControllerFactory for now

**Pull request merged**
